<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Version>10.0.1</Version>
        <Title>DotNetCore.Cap.RequestReply</Title>
        <AssemblyVersion>10.0.1</AssemblyVersion>
        <PackageId>DotNetCore.Cap.RequestReply</PackageId>
        <Authors>CoderHope</Authors>
        <Description>Request/Reply extension for DotNetCore.CAP.</Description>
        <PackageTags>CAP;RequestReply;Messaging;Redis;PostgreSQL;MySQL</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/CoderHope/DotNetCore.Cap.RequestReply</PackageProjectUrl>
        <RepositoryUrl>https://github.com/CoderHope/DotNetCore.Cap.RequestReply.git</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="DotNetCore.CAP" Version="10.0.1" />
      <PackageReference Include="MySqlConnector" Version="2.5.0" />
      <PackageReference Include="Npgsql" Version="9.0.4" />
      <PackageReference Include="StackExchange.Redis" Version="2.9.32" />
    </ItemGroup>

</Project>
